"""Contextual prefix generation for retrieval (SPEC §5.2 step 5, §5.5).

For each node a 1-2 sentence summary is generated by gpt-4o-mini, then a
structured prefix is prepended to node.text. The prefix-free body is stored in
node.metadata["original_text"] so the synthesis step can feed the LLM clean text
without the prefix noise.
"""

from llama_index.core.schema import TextNode
from llama_index.llms.openai import OpenAI

from rag_case_products.config import LLM_MODEL
from rag_case_products.models import DocType

_SUMMARY_PROMPT = (
    "You are a concise technical summarizer. Write exactly 1-2 sentences summarizing "
    "the following chunk of text. Do not add any information not present in the text. "
    "Do not speculate.\n\nCHUNK:\n{chunk}"
)

_CHUNK_TEXT_LIMIT = 3000

_llm = OpenAI(model=LLM_MODEL, temperature=0)


def _generate_summary(text: str) -> str:
    prompt = _SUMMARY_PROMPT.format(chunk=text[:_CHUNK_TEXT_LIMIT])
    return _llm.complete(prompt).text.strip()


def _build_product_prefix(meta: dict, summary: str) -> str:
    model_name = meta.get("model_name", "")
    category = meta.get("category", "")
    subcategory = meta.get("subcategory", "")
    section_path = meta.get("section_path", "")
    node_kind = meta.get("node_kind", "")
    category_str = f"{category}/{subcategory}" if subcategory else category
    return (
        f"[Product: {model_name} | Category: {category_str}"
        f" | Section: {section_path} | Kind: {node_kind}]\n{summary}"
    )


def _build_case_prefix(meta: dict, summary: str) -> str:
    title = meta.get("title", "")
    customer = meta.get("customer", "")
    industry = meta.get("industry", "")
    region = meta.get("region", "")
    year = meta.get("deployment_year", "")
    section = meta.get("section_path", "")
    node_kind = meta.get("node_kind", "")
    return (
        f"[Case: {title} | Customer: {customer} | Industry: {industry}"
        f" | Region: {region} | Year: {year}"
        f" | Section: {section} | Kind: {node_kind}]\n{summary}"
    )


def add_contextual_prefix(node: TextNode) -> None:
    """Mutate node in-place with a structured header + LLM summary prepended.

    original_text is kept in metadata so synthesis can feed the LLM clean body
    text. Summary is generated solely from the chunk to prevent hallucinations.
    """
    original = node.text
    summary = _generate_summary(original)
    meta = node.metadata
    doc_type = DocType(meta.get("doc_type", DocType.PRODUCT.value))

    if doc_type == DocType.PRODUCT:
        prefix = _build_product_prefix(meta, summary)
    else:
        prefix = _build_case_prefix(meta, summary)

    node.metadata["original_text"] = original
    node.text = f"{prefix}\n\n{original}"
    # Exclude all metadata keys from embedding and LLM content: the contextual
    # prefix is already inside node.text, so metadata must not be prepended again
    # (SPEC §5.5: embedding computed once over the prefixed text only).
    all_keys = list(node.metadata.keys())
    node.excluded_embed_metadata_keys = all_keys
    node.excluded_llm_metadata_keys = all_keys


def add_contextual_prefixes(nodes: list[TextNode]) -> None:
    for node in nodes:
        add_contextual_prefix(node)
